### ISSUE TITLE
Incorrect assertion when using circular dependencies

### ISSUE THREAD

**Issue by tikotzky** [dozoisch/babel-plugin-import-asserts#2]
If you have 2 files

``` js
// a.js
import b from './b';

export default 'from file a';

setTimeout(() => {
  console.log(b);
}, 0);
```

and

``` js
// b.js
import a from './a';

export default 'from file b';

setTimeout(() => {
  console.log(a);
}, 0);
```

if you run it like `babel-node a.js` it will correctly log

```
from file a
from file b
```

however if you compile using this plugin you will get an assertion in `b.js` stating that the import of `a` is undefined.

This can be fixed by wrapping the assertion in a `setTimeout` which would allow the circular dependencies to be resolved before firing the assertion.

**Comment by dozoisch** [comment]
2.1

**Comment by tikotzky** [comment]
Thanks!
