### ISSUE TITLE
Cannot read property 'isExpressionStatement' of null when using Babel stage 1

### ISSUE THREAD

**Issue by idolize** [dozoisch/babel-plugin-import-asserts#4]
I'm getting the following error after updating from Babel 5 to Babel 6 and 2.1.0 of babel-plugin-import-asserts:

```
Module build failed: TypeError: /client/state/router/actions/index.js: Cannot read property 'isExpressionStatement' of null
    at NodePath.insertAfter (/node_modules/babel-traverse/lib/path/modification.js:165:22)
    at /node_modules/babel-plugin-import-asserts/lib/index.js:28:16
    at Array.map (native)
    at PluginPass.ImportDeclaration (/node_modules/babel-plugin-import-asserts/lib/index.js:27:30)
```

This error is occurring for multiple files, each of which is using the [`export * from './something.js'` syntax](https://github.com/leebyron/ecmascript-more-export-from), which is part of the Babel [stage-1 preset](http://babeljs.io/docs/plugins/preset-stage-1/) and used to work with Babel 5 / babel-plugin-import-asserts version 1.0.2.

**Comment by dozoisch** [comment]
I'll check it up! Sorry for the delay. Might take me a bit of time as the update to babel 6 was done by an external contributor and none of my projects are on babel 6 now, so I have to figure out what could cause this.

**Comment by idolize** [comment]
Thanks! I appreciate it. This plugin is super useful :smile:

**Comment by dozoisch** [comment]
@idolize can you tell me the exact babel version you are running? See my PR branch. I'm trying to get an error from tests, but it seems to be transforming correctly.

**Comment by dozoisch** [comment]
@idolize do you have any more info :-p? I still couldn't repro. See https://github.com/dozoisch/babel-plugin-import-asserts/pull/5

**Comment by idolize** [comment]
Hey- Sorry, I was working on my Babel 5 -> 6 update in a different branch, and now that I switch back everything seems to be working great! Perhaps it was something else in my build causing the issue. Apologies for the false alarm!
